from finrl_myself.torch_layers.cnn import create_cnn
from finrl_myself.torch_layers.mlp import create_mlp
from finrl_myself.torch_layers.d2rl import D2RL
from finrl_myself.torch_layers.densenet_block import DensenetBolck
from finrl_myself.torch_layers.resnet_block import ResnetBlock1, ResnetBlock2
from finrl_myself.torch_layers.DualingFore_StateAction import DualingFore_StateAction
from finrl_myself.torch_layers.DualingPost_ActorCritic import DualingPost_ActorCritic